
Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Link("REGISTER").Click @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Link("REGISTER")_;_script infofile_;_ZIP::ssf47.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebEdit("firstName").Set "s" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebEdit("firstName")_;_script infofile_;_ZIP::ssf48.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebEdit("lastName").Set "a" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebEdit("lastName")_;_script infofile_;_ZIP::ssf49.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebList("country").Select "INDIA" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebList("country")_;_script infofile_;_ZIP::ssf50.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebEdit("email").Set "userp" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebEdit("email")_;_script infofile_;_ZIP::ssf51.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebEdit("password").SetSecure "5d7f148dbffb384ecb7b298cb96c34be" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebEdit("password")_;_script infofile_;_ZIP::ssf52.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").WebEdit("confirmPassword").SetSecure "5d7f149197eb9e23b803e671cfb13640" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").WebEdit("confirmPassword")_;_script infofile_;_ZIP::ssf53.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").Image("register").Click 45,14 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 4").Image("register")_;_script infofile_;_ZIP::ssf54.xml_;_
Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours_2").Link("sign-in").Click @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Register: Mercury Tours 2").Link("sign-in")_;_script infofile_;_ZIP::ssf55.xml_;_
 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Sign-on: Mercury Tours").Image("Login")_;_script infofile_;_ZIP::ssf58.xml_;_
